### ISSUE TITLE
wont autoprefix

### ISSUE THREAD

**Issue by thegamerx1** [jescalan/autoprefixer-stylus#186]
```stylus --include-css -u autoprefixer-stylus -w "css.styl"```

input:
```styl
#h_menu
	color: #a5a5a5
	position: fixed
	width: 500px
	height: 300px
	top: 50%
	left: 50%
	margin-top: -150px
	margin-left: -250px
	background-color: #474747
	padding: 30px
	z-index: 1000
	box-shadow: 5px 5px 3px 3px rgba(0,0,0,0.35)
	background: linear-gradient(to bottom, white, black)
```
output:
```css
#h_menu {
  color: #a5a5a5;
  position: fixed;
  width: 500px;
  height: 300px;
  top: 50%;
  left: 50%;
  margin-top: -150px;
  margin-left: -250px;
  background-color: #474747;
  padding: 30px;
  z-index: 1000;
  box-shadow: 5px 5px 3px 3px rgba(0,0,0,0.35);
  background: linear-gradient(to bottom, #fff, #000);
}
```
